### ISSUE TITLE
Zvýšit zabezpečení hesla a dalších údajů

### ISSUE THREAD

**Issue by triceo** [triceo/robozonky#102]
- Heslo ke keystore na příkazové řádce osolit nebo alespoň base64 encode.
- Zvážit možnost zadání hesla z stdin při spuštění.
- Systémové properties jsou vidět v `ps ax`.
- Zabezpečení JMX?

**Comment by theerror** [comment]
Libilo by se mi: 
1. pri spusteni by si checknul svuj conf, jestli existuje a pokud ano, tak by se normalne spustil
2. pokud ne, zeptal by se na stdin na potrebne udaje (heslo do Z + username, eventualne dalsi privatni jako treba ID zonkoidu)
3. Vygeneruje si klic, kterym zasifruje keystore
4. klic si zasifrovane ulozi to conf souboru.

**Comment by triceo** [comment]
Ad heslo z příkazové řádky: právě mi zamergovali https://github.com/cbeust/jcommander/pull/334, takže až to vydají v nějaké veřejné verzi, bude po drobných úpravách robota možné heslo zadat ze standardního vstupu.

Co se týká JMX a nastavení přes properties, s tím bohužel nic udělat nepůjde. Properties tam musí být při spuštění JVM, a JVM je neumí načíst ze souboru. Ale existuje property, která alespoň heslo umí načíst ze souboru - je ale otázka, jestli to řešit. Kdo si chce nastavit JMX přes heslo, může si tu property nastavit sám. Nechci komplikovat nastavení 99 % uživatelům kvůli něčemu, co zbývající 1 % hravě zvládne samo.

Ad. kódování hesla - nad tím budu ještě přemýšlet. Podpora pro keystore existuje právě proto, aby bylo heslo do Zonky "skryté". Skrývat heslo pro skrývání hesla nevyřeší problém, že jde stejně jen o "security by obscurity".

**Comment by theerror** [comment]
JMX: jde spis o to, jestli je JMX a RMI (nebo na co to pouzivas) potreba? Pokud ne, pak bude lepsi to proste nezapinat, ne? 

Kodovani hesla: v tomhle mas pravdu, ten keystore s vlastnim heslem je asi vcelku dostacujici, jen bych tohle udelal "by deafault" automaticky - proste zadas heslo do zonky pri prvnim spusteni/instalaci, vytvori se keystore a ten se zasifruje nejakym vygenerovanym heslem, ktere se ulozi do konfiguraku. Davalo by mi to asi nejvic logiku... Jestli pak uz resit heslo v konfiguraku v plaintextu nebo zasifrovane - to uz je spis filozoficka debata... faktem je, ze heslo v konfiguraku jeste nekoho oproti keystoru pouzit napadne, ale jestli se mu bude chtit hledat v kodu, jak se kryptovane?

**Comment by triceo** [comment]
V instalátoru už to tak funguje - ten automaticky generuje keystore s vlastním heslem. Do budoucna předpokládám, že noví uživatelé půjdou primárně přes instalátor.

Co se JMX týká, asi by byl dobrý nápad, aby to bylo ve výchozím nastavení vypnuté, a tedy bez těch properties. Není to zrovna funkcionalita, která by se nějak týkala obyčejných uživatelů - a pro pokročilé se to dá zdokumentovat.

**Comment by triceo** [comment]
Po výše uvedených změnách:

- Už není na příkazové řádce vyžadováno heslo.
- Vzdálená správa je ve výchozím nastavení vypnutá.
- Drtivou většinu properties lze načítat ze souboru namísto z příkazové řádky.

Za mne hotovo.
