### ISSUE TITLE
Notifikace do souborů by mělo jít vypnout

### ISSUE THREAD

**Issue by triceo** [triceo/robozonky#105]
Při investování _RoboZonky_ vytváří soubory s informacemi o tom, která půjčka byla investována, přeskočena atd. Těch souborů potenciálně může být docela rychle docela dost. Chtělo by to přidat vypínač.

**Comment by theerror** [comment]
Workaround:
Do cronu pridat:
`md5sum *.skipped | sort | awk 'BEGIN{lasthash = ""} $1 == lasthash {print $2} {lasthash = $1}' | xargs rm`

Vypujceno z
http://unix.stackexchange.com/questions/192701/how-to-remove-duplicate-files-using-bash
