### ISSUE TITLE
Robozonky ignoruje logback.xml

### ISSUE THREAD

**Issue by onovy** [triceo/robozonky#118]
Jak ve slozce kde je nainstalovan, tak v aktualni slouzce.

Nastaveni
```
-Dlogback.configurationFile=<absolutni cesta>
````
pomohlo.

**Comment by triceo** [comment]
Not a bug. :-)

Instalátor tu property nastaví. Jinak si uživatel musí nastavit, co uzná za vhodné, sám.

**Comment by triceo** [comment]
(Změnilo se to teď v 3.2.0 - vydal jsem se cestou, že v `robozonky.bat` / `robozonky.sh` nebudou nastavené žádné properties. Namísto toho vzniknul soubor `robozonky.properties`, kam si lidi můžou nastavit cokoliv, co uznají za vhodné.)

**Comment by onovy** [comment]
chapu, ale tim padem chybi zminka v:
https://github.com/triceo/robozonky/wiki/Co-nov%C3%A9ho-ve-verzi-3.2.0
a
https://github.com/triceo/robozonky/wiki/Jak-nastavit-logov%C3%A1n%C3%AD

**Comment by triceo** [comment]
To je dobrá poznámka. Uvědomil jsem si až po vydání 3.2.0, že se to vlastně lidem "rozbije" - a už jsem zapomněl aktualizovat dokumentaci.
