### ISSUE TITLE
NPE pokud je prázdné portfolio

### ISSUE THREAD

**Issue by davidmach14** [triceo/robozonky#33]
Spouštím RoboZonky v DRY režimu a dochází k této výjimce:
`ERROR Unexpected error.
java.lang.NullPointerException: null
        at com.github.triceo.robozonky.PortfolioOverview.calculate(PortfolioOverview.java:55)
        at com.github.triceo.robozonky.Investor.investOnce(Investor.java:162)
        at com.github.triceo.robozonky.Investor.invest(Investor.java:194)
        at com.github.triceo.robozonky.app.App.invest(App.java:217)
        at com.github.triceo.robozonky.app.App.main(App.java:146)
`
Tipuji, že je to způsobené tím, že spouštím RoboZonky nad úplně novým účtem, který má sice naplněnou peněženku, ale zatím žádnou investici. 
Log je v přiloženém souboru [robozonky.txt](https://github.com/triceo/robozonky/files/380447/robozonky.txt).

**Comment by triceo** [comment]
Zvláštní, přísahal bych, že jsem na to psal test. Každopádně díky za nahlášení, zítra se na to podívám a vydám 1.3.3 s opravou.

**Comment by triceo** [comment]
Nakonec jsem neodolal. :-) Dokážete přes Maven zkompilovat aktuální verzi větve 1.3.x a říct mi, jestli řeší váš problém? (Myslím, že ano, ale rád bych si byl jist.)

**Comment by davidmach14** [comment]
Na větvi 1.3.x se to bohužel projevuje stejně. Rád bych pomohl, ale Java není můj šálek čaje...
Maven 3.3.9
Oracle JDK 1.8.0_101

**Comment by triceo** [comment]
Tak to prosím zkuste ještě jednou, ale stáhněte si nejnovější změny. Jsem si tentokrát na 99 % jistý, že jsem našel všechna místa, která by to mohla vyvolat.

**Comment by davidmach14** [comment]
Vyzkoušel jsem znovu zkompilovat větev 1.3.3, kam jste propsal tu úpravu, ale dopracoval jsem se ke stejnému výsledku. Stejně tak na master větvi...
BTW dnes jsem poprvé investoval, takže až Zonky zapracuje tu půjčku, tak už nebudu mít portfolio prázdné a možná tak přestanu být testerem (této chyby)...

**Comment by triceo** [comment]
V tom případě jsem právě udělal poslední zoufalý pokus, a ještě mi dejte jednu šanci.
(Touhle změnou jsem definitivně vyčerpal všechny možnosti.)

**Comment by davidmach14** [comment]
Tak už jsem to bohužel nestačil vyzkoušet - dnes ráno se moje první investice objevila na dashboardu v Zonky a Robozonky funguje podle očekávání bezproblémově...

**Comment by triceo** [comment]
Každopádně děkuji! Já vydám, co mám, a budu doufat, že to problém vyřešilo - protože beztak už nemám žádné další nápady, kde by to ještě mohlo být.
