### ISSUE TITLE
Úložiště přihlašovacích údajů se nevytvoří s chybnou strategií

### ISSUE THREAD

**Issue by frantisekz** [triceo/robozonky#34]
Pokud mám v souboru s nastavením inevstiční strategie chybu, tak se soubor s uloženým jménem a heslem nevytvoří, i když robzonky vypíše:
`Guarded storage has been created with your username and password: robozonky.keystore`

**Comment by triceo** [comment]
Zajímavé. Podívám se na to během týdne. Díky za nahlášení!

**Comment by triceo** [comment]
Párkrát se mi nepovedl commit, jak je vidno. :-) Nicméně oprava bude během několika hodin na mirrorech, verze 1.3.4.
