### ISSUE TITLE
Pouziti pouze maximumLoanAmount.default

### ISSUE THREAD

**Issue by WojtylaCZ** [triceo/robozonky#51]
Spis Feature Request.
Situace: Je mi jedno jaka moje investice bude mit podil v celkove pujcce, ale maximalne investuji napr. 1000 CZK do jedne pujcky. (Nejnizsi pujcky jsou 20k, 30k+ a to je jeste ojedinele, takze podily jsou stejne v radech jednotek a nizsich radu procent). Je to relevantni user story nebo jen muj vymysl?

Idealni situace: v cfg souboru specifikuji jen: maximumLoanAmount.default  = 1000. Bez maximumLoanShare.XXX 

Nyni to vyhodi Exception java.lang.IllegalStateException: Investment strategy is incomplete. Missing value for 'maximumLoanShare' and rating 'AAAAA'. Domnivam se, ze z SimpleInvestmentStrategyService, funkce getValue().

Ano, workaround je zrejmy, predpokladam ze stejny vysledek ma nastaveni pro vsechny na maximumLoanShare.XXX = 1. Ci jinou vysokou hodnotu. Ale jsou to radky nastaveni navic.

Ano, Ne?

**Comment by triceo** [comment]
To, že jsou všechny položky ve strategii povinné, má svůj důvod - nechci, aby se uživatelé spoléhali na jakékoliv výchozí hodnoty. Naopak chci, aby uživatelé udělali svá investiční rozhodnutí vědomě, a nebudu tedy parametry strategie dělat volitelné. 

Použití konvence `default` namísto konkrétního ratingu dokáže snížit počet řádků na nezbytné minimum. Alternativně by se dala použít `rule-based` strategie, která uživatele neomezuje prakticky nijak, ale to už je poměrně pokročilé téma.

Nicméně ta poznámka, že velká část půjček je relativně nízká a podíly tedy nedávají velký smysl, je oprávněná. Nedomnívám se však, že v tomhle případě je přidaná hodnota několika chybějících řádků ve strategii tak vysoká, aby vyvážila potenciální uživatele, kteří z nevědomosti hloupě investovali.

I když Vám tentokrát nevyhovím, i tak děkuji za názor!
