### ISSUE TITLE
Běh na NASu od Synology

### ISSUE THREAD

**Issue by kudykam** [triceo/robozonky#52]
Ahoj,
spustil sem tento skript jako úlohu na Synology Discstation 6 , kde běží java 8. Vrací mi to tuhle hlášku:
`13:23:19.016 [main] INFO com.github.triceo.robozonky.app.App - RoboZonky v1.4.2 loading.
13:23:19.051 [main] DEBUG com.github.triceo.robozonky.app.App - Running Oracle Corporation Java v1.8.0_65 on Linux v3.2.40 (arm, en_US).
13:23:19.991 [main] DEBUG com.github.triceo.robozonky.app.CommandLineInterface - Processing command line: [-s moje.cfg, -u xxx@seznam.cz].
13:23:20.790 [main] ERROR com.github.triceo.robozonky.app.AuthenticationHandlerProvider - Failed reading guarded storage.
java.security.KeyStoreException: JCEKS not found
	at java.security.KeyStore.getInstance(KeyStore.java:851)
	at com.github.triceo.robozonky.app.util.KeyStoreHandler.create(KeyStoreHandler.java:76)
	at com.github.triceo.robozonky.app.AuthenticationHandlerProvider.newSecretProvider(AuthenticationHandlerProvider.java:39)
	at com.github.triceo.robozonky.app.AuthenticationHandlerProvider.getSecretProvider(AuthenticationHandlerProvider.java:81)
	at com.github.triceo.robozonky.app.AuthenticationHandlerProvider.apply(AuthenticationHandlerProvider.java:105)
	at com.github.triceo.robozonky.app.App.processCommandLine(App.java:59)
	at com.github.triceo.robozonky.app.App.main(App.java:85)
Caused by: java.security.NoSuchAlgorithmException: JCEKS KeyStore not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.KeyStore.getInstance(KeyStore.java:848)
	... 6 common frames omitted
13:23:21.606 [main] DEBUG com.github.triceo.robozonky.app.App - RoboZonky terminating with 'ERROR_WRONG_PARAMETERS' return code.`

V čem může být problém?

**Comment by triceo** [comment]
Zajímavé - sám totiž RoboZonky taky provozuji na Synology NAS s DiskStation 6 a Javou 8! :-)

Můžete zjistit přesnou verzi Javy, kterou používáte? A jak jste ji tam nainstaloval?
Moje je přímo z Package Center.

**Comment by triceo** [comment]
Pardon, verze Javy je v logu. :-) Vaše je:
`Oracle Corporation Java v1.8.0_65 on Linux v3.2.40 (arm, en_US)`

Moje je:
`Oracle Corporation Java v1.8.0_60 on Linux v3.2.40 (i386, en_US).`

Takže dva hlavní rozdíly:

- Vaše Synology běží na ARMu, moje na x86.
- Vaše Synology má o něco novější verzi Javy než moje.

Tipnu si, že absence JCEKS bude souviset s tím prvním. Ve volné chvíli zjistím, je-li tomu tak.

**Comment by triceo** [comment]
@kudykam K tomuhle komentáři přikládám soubor "SecurityProviderCheck.class" - je to Javovská třída, kterou bych rád, abyste na Vašem NASu spustil a poslal mi její textový výstup. (V terminálu stačí napsat `java SecurityProviderCheck`.)

Z výstupu poznám, které `Provider`y vaše Java poskytuje, a porovnám to se svými - díky tomu se mi podaří napsat takovou implementaci, která půjde nám oběma.
[SecurityProviderCheck.zip](https://github.com/triceo/robozonky/files/453280/SecurityProviderCheck.zip)

**Comment by kudykam** [comment]
Možná to dělám blbě, ale spustil sem SecurityProviderCheck.java to jako naplánovanou ulohu a výstupem bylo toto:
```
/volume1/public/test/SecurityProviderCheck.java: line 1: import: command not found
/volume1/public/test/SecurityProviderCheck.java: line 2: import: command not found
/volume1/public/test/SecurityProviderCheck.java: line 3: import: command not found
/volume1/public/test/SecurityProviderCheck.java: line 4: import: command not found
/volume1/public/test/SecurityProviderCheck.java: line 6: public: command not found
/volume1/public/test/SecurityProviderCheck.java: line 8: syntax error near unexpected token `('
/volume1/public/test/SecurityProviderCheck.java: line 8: `    public static void main(final String[] args) {'

```

**Comment by triceo** [comment]
Pokud to spouštíte jako naplánovanou úlohu, dejte tam `java /volume1/public/test/SecurityProviderCheck`.

**Comment by kudykam** [comment]
sh: /volume1/public/test/SecurityProviderCheck.: No such file or directory

**Comment by triceo** [comment]
Dobře, vymyslím to někdy během dneška jinak. :-)

**Comment by kudykam** [comment]
sh: java: command not found

pokud spustím jako
`/volume1/@appstore/java8/ejdk1.8.0_65/linux_arm_sflt/jre/bin/java /volume1/public/test/SecurityProviderCheck`
tak vrátí
Error: Could not find or load main class .volume1.public.test.SecurityProviderCheck

**Comment by triceo** [comment]
Tak, teď už jsem to snad udělal neprůstřelné. Přikládám ZIP soubor, který obsahuje JAR soubor.
[SecurityProviderCheck.zip](https://github.com/triceo/robozonky/files/453888/SecurityProviderCheck.zip). Tenhle JAR soubor stačí spustit příkazem `java -jar SecurityProvideCheck.jar`.

Výsledkem bude výpis na standarní výstup. Kdyby se ho snad nepodařilo získat, hledejte soubor `SecurityProviderCheck.log`, který bude obsahovat identickou kopii.

**Comment by kudykam** [comment]
Skript:
`/volume1/@appstore/java8/ejdk1.8.0_65/linux_arm_sflt/jre/bin/java -jar /volume1/public/test/SecurityProvideCheck.jar
`
Výsledek:
Error: Unable to access jarfile /volume1/public/test/SecurityProvideCheck.jar
Skript:
`java -jar /volume1/public/test/SecurityProvideCheck.jar`
Výsledek:
sh: java: command not found

Z nějakého důvodu javu spouští jen zadáním celé cesty (i u robozonky skritpu)

**Comment by triceo** [comment]
Ten první příkaz bude fungovat - akorát místo `SecurityProvideCheck` napište `SecurityProviderCheck` - chybí vám tam `r`. Měl jsem ve svém původním komentáři překlep, který jsem potom opravil.

**Comment by kudykam** [comment]
`Exception in thread "main" java.io.FileNotFoundException: SecurityProviderCheck.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at SecurityProviderCheck.main(SecurityProviderCheck.java:23)`

**Comment by triceo** [comment]
Potřebujete mít práva pro zápis v adresáři, že kterého program spouštíte. S tím už já nic neudělám.

**Comment by kudykam** [comment]
Vidím vidím, spouštím jako admin a ten určitě má práva do public... divný

**Comment by triceo** [comment]
Problém pravděpodobně není v tom, kde je ten JAR přítomen, ale odkud se spouští. Musíte mít práva pro zápis v pracovním adresáři. Teď už střílím fakt naslepo, ale něco takového by mohlo fungovat:

`cd /volume1/homes/admin && /volume1/@appstore/java8/ejdk1.8.0_65/linux_arm_sflt/jre/bin/java -jar /volume1/homes/admin/SecurityProviderCheck.jar `

(Nejdřív se přepnout do `home`, abychom měli práva, a následně tam hned ten program spustit.)

**Comment by kudykam** [comment]
žeby?
`    Name: SUN
 Version: 1.8
    Info: SUN (DSA key/parameter generation; DSA signing; SHA-1, MD5 digests; SecureRandom; X.509 certificates; JKS & DKS keystores; PKIX CertPathValidator; PKIX CertPathBuilder; LDAP, Collection CertStores, JavaPolicy Policy; JavaLoginConfig Configuration)
Services: [SUN: SecureRandom.NativePRNG -> sun.security.provider.NativePRNG
, SUN: SecureRandom.SHA1PRNG -> sun.security.provider.SecureRandom
  attributes: {ImplementedIn=Software}
, SUN: SecureRandom.NativePRNGBlocking -> sun.security.provider.NativePRNG$Blocking
, SUN: SecureRandom.NativePRNGNonBlocking -> sun.security.provider.NativePRNG$NonBlocking
, SUN: Signature.SHA1withDSA -> sun.security.provider.DSA$SHA1withDSA
  aliases: [DSA, DSS, SHA/DSA, SHA-1/DSA, SHA1/DSA, SHAwithDSA, DSAWithSHA1, OID.1.2.840.10040.4.3, 1.2.840.10040.4.3, 1.3.14.3.2.13, 1.3.14.3.2.27]
  attributes: {ImplementedIn=Software, KeySize=1024, SupportedKeyClasses=java.security.interfaces.DSAPublicKey|java.security.interfaces.DSAPrivateKey}
, SUN: Signature.NONEwithDSA -> sun.security.provider.DSA$RawDSA
  aliases: [RawDSA]
  attributes: {KeySize=1024, SupportedKeyClasses=java.security.interfaces.DSAPublicKey|java.security.interfaces.DSAPrivateKey}
, SUN: Signature.SHA224withDSA -> sun.security.provider.DSA$SHA224withDSA
  aliases: [OID.2.16.840.1.101.3.4.3.1, 2.16.840.1.101.3.4.3.1]
  attributes: {KeySize=2048, SupportedKeyClasses=java.security.interfaces.DSAPublicKey|java.security.interfaces.DSAPrivateKey}
, SUN: Signature.SHA256withDSA -> sun.security.provider.DSA$SHA256withDSA
  aliases: [OID.2.16.840.1.101.3.4.3.2, 2.16.840.1.101.3.4.3.2]
  attributes: {KeySize=2048, SupportedKeyClasses=java.security.interfaces.DSAPublicKey|java.security.interfaces.DSAPrivateKey}
, SUN: KeyPairGenerator.DSA -> sun.security.provider.DSAKeyPairGenerator
  aliases: [OID.1.2.840.10040.4.1, 1.2.840.10040.4.1, 1.3.14.3.2.12]
  attributes: {ImplementedIn=Software, KeySize=2048}
, SUN: MessageDigest.MD2 -> sun.security.provider.MD2
, SUN: MessageDigest.MD5 -> sun.security.provider.MD5
  attributes: {ImplementedIn=Software}
, SUN: MessageDigest.SHA -> sun.security.provider.SHA
  aliases: [SHA-1, SHA1, 1.3.14.3.2.26, OID.1.3.14.3.2.26]
  attributes: {ImplementedIn=Software}
, SUN: MessageDigest.SHA-224 -> sun.security.provider.SHA2$SHA224
  aliases: [2.16.840.1.101.3.4.2.4, OID.2.16.840.1.101.3.4.2.4]
, SUN: MessageDigest.SHA-256 -> sun.security.provider.SHA2$SHA256
  aliases: [2.16.840.1.101.3.4.2.1, OID.2.16.840.1.101.3.4.2.1]
, SUN: MessageDigest.SHA-384 -> sun.security.provider.SHA5$SHA384
  aliases: [2.16.840.1.101.3.4.2.2, OID.2.16.840.1.101.3.4.2.2]
, SUN: MessageDigest.SHA-512 -> sun.security.provider.SHA5$SHA512
  aliases: [2.16.840.1.101.3.4.2.3, OID.2.16.840.1.101.3.4.2.3]
, SUN: AlgorithmParameterGenerator.DSA -> sun.security.provider.DSAParameterGenerator
  attributes: {ImplementedIn=Software, KeySize=2048}
, SUN: AlgorithmParameters.DSA -> sun.security.provider.DSAParameters
  aliases: [OID.1.2.840.10040.4.1, 1.2.840.10040.4.1, 1.3.14.3.2.12]
  attributes: {ImplementedIn=Software}
, SUN: KeyFactory.DSA -> sun.security.provider.DSAKeyFactory
  aliases: [OID.1.2.840.10040.4.1, 1.2.840.10040.4.1, 1.3.14.3.2.12]
  attributes: {ImplementedIn=Software}
, SUN: CertificateFactory.X.509 -> sun.security.provider.X509Factory
  aliases: [X509]
  attributes: {ImplementedIn=Software}
, SUN: KeyStore.JKS -> sun.security.provider.JavaKeyStore$DualFormatJKS
  attributes: {ImplementedIn=Software}
, SUN: KeyStore.CaseExactJKS -> sun.security.provider.JavaKeyStore$CaseExactJKS
, SUN: KeyStore.DKS -> sun.security.provider.DomainKeyStore$DKS
, SUN: Policy.JavaPolicy -> sun.security.provider.PolicySpiFile
, SUN: Configuration.JavaLoginConfig -> sun.security.provider.ConfigFile$Spi
, SUN: CertPathBuilder.PKIX -> sun.security.provider.certpath.SunCertPathBuilder
  attributes: {ImplementedIn=Software, ValidationAlgorithm=RFC3280}
, SUN: CertPathValidator.PKIX -> sun.security.provider.certpath.PKIXCertPathValidator
  attributes: {ImplementedIn=Software, ValidationAlgorithm=RFC3280}
, SUN: CertStore.LDAP -> sun.security.provider.certpath.ldap.LDAPCertStore
  attributes: {ImplementedIn=Software, LDAPSchema=RFC2587}
, SUN: CertStore.Collection -> sun.security.provider.certpath.CollectionCertStore
  attributes: {ImplementedIn=Software}
, SUN: CertStore.com.sun.security.IndexedCollection -> sun.security.provider.certpath.IndexedCollectionCertStore
  attributes: {ImplementedIn=Software}
]
==========
    Name: SunEC
 Version: 1.8
    Info: Sun Elliptic Curve provider (EC, ECDSA, ECDH)
Services: [SunEC: KeyFactory.EC -> sun.security.ec.ECKeyFactory
  aliases: [EllipticCurve]
  attributes: {ImplementedIn=Software}
, SunEC: AlgorithmParameters.EC -> sun.security.ec.ECParameters
  aliases: [EllipticCurve, 1.2.840.10045.2.1]
  attributes: {ImplementedIn=Software, KeySize=256, SupportedCurves=[secp112r1,1.3.132.0.6]|[secp112r2,1.3.132.0.7]|[secp128r1,1.3.132.0.28]|[secp128r2,1.3.132.0.29]|[secp160k1,1.3.132.0.9]|[secp160r1,1.3.132.0.8]|[secp160r2,1.3.132.0.30]|[secp192k1,1.3.132.0.31]|[secp192r1,NIST P-192,X9.62 prime192v1,1.2.840.10045.3.1.1]|[secp224k1,1.3.132.0.32]|[secp224r1,NIST P-224,1.3.132.0.33]|[secp256k1,1.3.132.0.10]|[secp256r1,NIST P-256,X9.62 prime256v1,1.2.840.10045.3.1.7]|[secp384r1,NIST P-384,1.3.132.0.34]|[secp521r1,NIST P-521,1.3.132.0.35]|[X9.62 prime192v2,1.2.840.10045.3.1.2]|[X9.62 prime192v3,1.2.840.10045.3.1.3]|[X9.62 prime239v1,1.2.840.10045.3.1.4]|[X9.62 prime239v2,1.2.840.10045.3.1.5]|[X9.62 prime239v3,1.2.840.10045.3.1.6]|[sect113r1,1.3.132.0.4]|[sect113r2,1.3.132.0.5]|[sect131r1,1.3.132.0.22]|[sect131r2,1.3.132.0.23]|[sect163k1,NIST K-163,1.3.132.0.1]|[sect163r1,1.3.132.0.2]|[sect163r2,NIST B-163,1.3.132.0.15]|[sect193r1,1.3.132.0.24]|[sect193r2,1.3.132.0.25]|[sect233k1,NIST K-233,1.3.132.0.26]|[sect233r1,NIST B-233,1.3.132.0.27]|[sect239k1,1.3.132.0.3]|[sect283k1,NIST K-283,1.3.132.0.16]|[sect283r1,NIST B-283,1.3.132.0.17]|[sect409k1,NIST K-409,1.3.132.0.36]|[sect409r1,NIST B-409,1.3.132.0.37]|[sect571k1,NIST K-571,1.3.132.0.38]|[sect571r1,NIST B-571,1.3.132.0.39]|[X9.62 c2tnb191v1,1.2.840.10045.3.0.5]|[X9.62 c2tnb191v2,1.2.840.10045.3.0.6]|[X9.62 c2tnb191v3,1.2.840.10045.3.0.7]|[X9.62 c2tnb239v1,1.2.840.10045.3.0.11]|[X9.62 c2tnb239v2,1.2.840.10045.3.0.12]|[X9.62 c2tnb239v3,1.2.840.10045.3.0.13]|[X9.62 c2tnb359v1,1.2.840.10045.3.0.18]|[X9.62 c2tnb431r1,1.2.840.10045.3.0.20]}
, SunEC: Signature.NONEwithECDSA -> sun.security.ec.ECDSASignature$Raw
  attributes: {ImplementedIn=Software, SupportedKeyClasses=java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey}
, SunEC: Signature.SHA1withECDSA -> sun.security.ec.ECDSASignature$SHA1
  aliases: [OID.1.2.840.10045.4.1, 1.2.840.10045.4.1]
  attributes: {ImplementedIn=Software, KeySize=256, SupportedKeyClasses=java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey}
, SunEC: Signature.SHA224withECDSA -> sun.security.ec.ECDSASignature$SHA224
  aliases: [OID.1.2.840.10045.4.3.1, 1.2.840.10045.4.3.1]
  attributes: {ImplementedIn=Software, SupportedKeyClasses=java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey}
, SunEC: Signature.SHA256withECDSA -> sun.security.ec.ECDSASignature$SHA256
  aliases: [OID.1.2.840.10045.4.3.2, 1.2.840.10045.4.3.2]
  attributes: {ImplementedIn=Software, SupportedKeyClasses=java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey}
, SunEC: Signature.SHA384withECDSA -> sun.security.ec.ECDSASignature$SHA384
  aliases: [OID.1.2.840.10045.4.3.3, 1.2.840.10045.4.3.3]
  attributes: {ImplementedIn=Software, SupportedKeyClasses=java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey}
, SunEC: Signature.SHA512withECDSA -> sun.security.ec.ECDSASignature$SHA512
  aliases: [OID.1.2.840.10045.4.3.4, 1.2.840.10045.4.3.4]
  attributes: {ImplementedIn=Software, SupportedKeyClasses=java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey}
, SunEC: KeyPairGenerator.EC -> sun.security.ec.ECKeyPairGenerator
  aliases: [EllipticCurve]
  attributes: {ImplementedIn=Software, KeySize=256}
, SunEC: KeyAgreement.ECDH -> sun.security.ec.ECDHKeyAgreement
  attributes: {ImplementedIn=Software, SupportedKeyClasses=java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey}
]
==========
    Name: SunJGSS
 Version: 1.8
    Info: Sun (Kerberos v5, SPNEGO)
Services: [SunJGSS: GssApiMechanism.1.2.840.113554.1.2.2 -> sun.security.jgss.krb5.Krb5MechFactory
, SunJGSS: GssApiMechanism.1.3.6.1.5.5.2 -> sun.security.jgss.spnego.SpNegoMechFactory
]
==========
    Name: SunJSSE
 Version: 1.8
    Info: Sun JSSE provider(PKCS12, SunX509/PKIX key/trust factories, SSLv3/TLSv1/TLSv1.1/TLSv1.2)
Services: [SunJSSE: KeyFactory.RSA -> sun.security.rsa.RSAKeyFactory
  aliases: [1.2.840.113549.1.1, OID.1.2.840.113549.1.1]
, SunJSSE: KeyPairGenerator.RSA -> sun.security.rsa.RSAKeyPairGenerator
  aliases: [1.2.840.113549.1.1, OID.1.2.840.113549.1.1]
, SunJSSE: Signature.MD2withRSA -> sun.security.rsa.RSASignature$MD2withRSA
  aliases: [1.2.840.113549.1.1.2, OID.1.2.840.113549.1.1.2]
, SunJSSE: Signature.MD5withRSA -> sun.security.rsa.RSASignature$MD5withRSA
  aliases: [1.2.840.113549.1.1.4, OID.1.2.840.113549.1.1.4]
, SunJSSE: Signature.SHA1withRSA -> sun.security.rsa.RSASignature$SHA1withRSA
  aliases: [1.2.840.113549.1.1.5, OID.1.2.840.113549.1.1.5, 1.3.14.3.2.29, OID.1.3.14.3.2.29]
, SunJSSE: Signature.MD5andSHA1withRSA -> sun.security.ssl.RSASignature
, SunJSSE: KeyManagerFactory.SunX509 -> sun.security.ssl.KeyManagerFactoryImpl$SunX509
, SunJSSE: KeyManagerFactory.NewSunX509 -> sun.security.ssl.KeyManagerFactoryImpl$X509
  aliases: [PKIX]
, SunJSSE: TrustManagerFactory.SunX509 -> sun.security.ssl.TrustManagerFactoryImpl$SimpleFactory
, SunJSSE: TrustManagerFactory.PKIX -> sun.security.ssl.TrustManagerFactoryImpl$PKIXFactory
  aliases: [SunPKIX, X509, X.509]
, SunJSSE: SSLContext.TLSv1 -> sun.security.ssl.SSLContextImpl$TLS10Context
  aliases: [SSLv3]
, SunJSSE: SSLContext.TLSv1.1 -> sun.security.ssl.SSLContextImpl$TLS11Context
, SunJSSE: SSLContext.TLSv1.2 -> sun.security.ssl.SSLContextImpl$TLS12Context
, SunJSSE: SSLContext.TLS -> sun.security.ssl.SSLContextImpl$TLSContext
  aliases: [SSL]
, SunJSSE: SSLContext.Default -> sun.security.ssl.SSLContextImpl$DefaultSSLContext
, SunJSSE: KeyStore.PKCS12 -> sun.security.pkcs12.PKCS12KeyStore
]
==========
    Name: SunPCSC
 Version: 1.8
    Info: Sun PC/SC provider
Services: [SunPCSC: TerminalFactory.PC/SC -> sun.security.smartcardio.SunPCSC$Factory
]
==========
    Name: SunRsaSign
 Version: 1.8
    Info: Sun RSA signature provider
Services: [SunRsaSign: KeyFactory.RSA -> sun.security.rsa.RSAKeyFactory
  aliases: [1.2.840.113549.1.1, OID.1.2.840.113549.1.1]
, SunRsaSign: KeyPairGenerator.RSA -> sun.security.rsa.RSAKeyPairGenerator
  aliases: [1.2.840.113549.1.1, OID.1.2.840.113549.1.1]
, SunRsaSign: Signature.MD2withRSA -> sun.security.rsa.RSASignature$MD2withRSA
  aliases: [1.2.840.113549.1.1.2, OID.1.2.840.113549.1.1.2]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunRsaSign: Signature.MD5withRSA -> sun.security.rsa.RSASignature$MD5withRSA
  aliases: [1.2.840.113549.1.1.4, OID.1.2.840.113549.1.1.4]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunRsaSign: Signature.SHA1withRSA -> sun.security.rsa.RSASignature$SHA1withRSA
  aliases: [1.2.840.113549.1.1.5, OID.1.2.840.113549.1.1.5, 1.3.14.3.2.29]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunRsaSign: Signature.SHA224withRSA -> sun.security.rsa.RSASignature$SHA224withRSA
  aliases: [1.2.840.113549.1.1.14, OID.1.2.840.113549.1.1.14]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunRsaSign: Signature.SHA256withRSA -> sun.security.rsa.RSASignature$SHA256withRSA
  aliases: [1.2.840.113549.1.1.11, OID.1.2.840.113549.1.1.11]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunRsaSign: Signature.SHA384withRSA -> sun.security.rsa.RSASignature$SHA384withRSA
  aliases: [1.2.840.113549.1.1.12, OID.1.2.840.113549.1.1.12]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunRsaSign: Signature.SHA512withRSA -> sun.security.rsa.RSASignature$SHA512withRSA
  aliases: [1.2.840.113549.1.1.13, OID.1.2.840.113549.1.1.13]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
]
==========
    Name: SunSASL
 Version: 1.8
    Info: Sun SASL provider(implements client mechanisms for: DIGEST-MD5, GSSAPI, EXTERNAL, PLAIN, CRAM-MD5, NTLM; server mechanisms for: DIGEST-MD5, GSSAPI, CRAM-MD5, NTLM)
Services: [SunSASL: SaslClientFactory.DIGEST-MD5 -> com.sun.security.sasl.digest.FactoryImpl
, SunSASL: SaslClientFactory.NTLM -> com.sun.security.sasl.ntlm.FactoryImpl
, SunSASL: SaslClientFactory.GSSAPI -> com.sun.security.sasl.gsskerb.FactoryImpl
, SunSASL: SaslClientFactory.EXTERNAL -> com.sun.security.sasl.ClientFactoryImpl
, SunSASL: SaslClientFactory.PLAIN -> com.sun.security.sasl.ClientFactoryImpl
, SunSASL: SaslClientFactory.CRAM-MD5 -> com.sun.security.sasl.ClientFactoryImpl
, SunSASL: SaslServerFactory.CRAM-MD5 -> com.sun.security.sasl.ServerFactoryImpl
, SunSASL: SaslServerFactory.GSSAPI -> com.sun.security.sasl.gsskerb.FactoryImpl
, SunSASL: SaslServerFactory.DIGEST-MD5 -> com.sun.security.sasl.digest.FactoryImpl
, SunSASL: SaslServerFactory.NTLM -> com.sun.security.sasl.ntlm.FactoryImpl
]
==========
    Name: XMLDSig
 Version: 1.8
    Info: XMLDSig (DOM XMLSignatureFactory; DOM KeyInfoFactory; C14N 1.0, C14N 1.1, Exclusive C14N, Base64, Enveloped, XPath, XPath2, XSLT TransformServices)
Services: [XMLDSig: TransformService.http://www.w3.org/2006/12/xml-c14n11#WithComments -> org.jcp.xml.dsig.internal.dom.DOMCanonicalXMLC14N11Method
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/2000/09/xmldsig#base64 -> org.jcp.xml.dsig.internal.dom.DOMBase64Transform
  aliases: [BASE64]
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/TR/1999/REC-xslt-19991116 -> org.jcp.xml.dsig.internal.dom.DOMXSLTTransform
  aliases: [XSLT]
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/2001/10/xml-exc-c14n# -> org.jcp.xml.dsig.internal.dom.DOMExcC14NMethod
  aliases: [EXCLUSIVE]
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments -> org.jcp.xml.dsig.internal.dom.DOMCanonicalXMLC14NMethod
  aliases: [INCLUSIVE_WITH_COMMENTS]
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/2000/09/xmldsig#enveloped-signature -> org.jcp.xml.dsig.internal.dom.DOMEnvelopedTransform
  aliases: [ENVELOPED]
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/2002/06/xmldsig-filter2 -> org.jcp.xml.dsig.internal.dom.DOMXPathFilter2Transform
  aliases: [XPATH2]
  attributes: {MechanismType=DOM}
, XMLDSig: XMLSignatureFactory.DOM -> org.jcp.xml.dsig.internal.dom.DOMXMLSignatureFactory
, XMLDSig: TransformService.http://www.w3.org/TR/2001/REC-xml-c14n-20010315 -> org.jcp.xml.dsig.internal.dom.DOMCanonicalXMLC14NMethod
  aliases: [INCLUSIVE]
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/2001/10/xml-exc-c14n#WithComments -> org.jcp.xml.dsig.internal.dom.DOMExcC14NMethod
  aliases: [EXCLUSIVE_WITH_COMMENTS]
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/2006/12/xml-c14n11 -> org.jcp.xml.dsig.internal.dom.DOMCanonicalXMLC14N11Method
  attributes: {MechanismType=DOM}
, XMLDSig: TransformService.http://www.w3.org/TR/1999/REC-xpath-19991116 -> org.jcp.xml.dsig.internal.dom.DOMXPathTransform
  aliases: [XPATH]
  attributes: {MechanismType=DOM}
, XMLDSig: KeyInfoFactory.DOM -> org.jcp.xml.dsig.internal.dom.DOMKeyInfoFactory
]
==========
`

**Comment by triceo** [comment]
Super, díky za spolupráci! :-) Porovnám to se svými výsledky a najdu nějaký funkční průnik.

**Comment by kudykam** [comment]
https://dl.dropboxusercontent.com/u/20802604/output.log

**Comment by triceo** [comment]
Najít nějakou implementaci, která funguje jak na ARM tak na PC, se ukazuje jako oříšek. Ale zatím to nevzdávám.

**Comment by triceo** [comment]
Poslední novinky na Zonky mi trochu zamíchaly prioritami, budu se tenhle víkend věnovat přípravě na zavedení CAPTCHA. Váš problém, doufám, vyřeším v 1.6.0.

**Comment by frantisekz** [comment]
Pokud by to mohlo něčemu pomoct, tak kdyžtak můžu zkusit testovat i u sebe. RoboZonky mi běží na ARMu (Allwinner H3/ARM7) celkem bez potíží (nedávno Fedora/OpenJDK, teď už Debian/OracleJDK). Nemám ale na routeru nastavené forwardování ssh a fyzicky se k tomu dostanu nejdřív v pondělí.

**Comment by triceo** [comment]
@frantisekz  Kdybys mohl spustit aplikaci z https://github.com/triceo/robozonky/issues/52#issuecomment-244598113 a poslat výstup, bylo by to super. Taky by mě zajímala konkrátní `java -version`, kterou na tom ARMu máš. Začíná to vypadat, že na ARMu se různé implementace chovají různě, což je vůbec nejhorší ze všech možností. :-)

**Comment by triceo** [comment]
@kudykam Můžete, prosím, něco vyzkoušet? Vezměte [tenhle soubor](https://www.bouncycastle.org/download/jce-jdk13-155.jar) a nahrajte ho do `/volume1/@appstore/java8/ejdk1.8.0_65/linux_arm_sflt/jre/lib/ext`. 

Pokud je má domněnka správná, váš problém by se tím měl vyřešit. Jedná se totiž o implementaci přesně těch knihoven, které ve vaší instalaci chybí.

**Comment by kudykam** [comment]
překopíroval sem soubor na uvedenou cestu, ale po spuštění hází furt stejnou chybu jak v prvním příspěvku. Akorát sem si všim že čas uvedený v logu je o hodinu nižší než systémový, ale to s tím asi nijak nesouvisí.

**Comment by triceo** [comment]
@kudykam Díky! Usuzuji z toho, že budu muset vymyslet nějaké nouzové řešení pro Váš případ, které nebude používat KeyStore.

**Comment by kudykam** [comment]
co to znamená? že to nepujde?

**Comment by triceo** [comment]
@kudykam Ve Vašem případě neexistuje jiná možnost, než zařídit, že se nebude KeyStore ani vytvářet, ani číst. Takže Vám sice RoboZonky bude fungovat, ale budete muset na příkazové řádce uvádět heslo do Zonky. Nicméně to není zas až takový problém - myslím, že většina lidí o žádné jiné možnosti ani neví. 

Někdy během týdne nebo dvou vydám verzi 1.6.0, kterou budete moci začít používat.
