### ISSUE TITLE
Primární zdroj dat Zotify

### ISSUE THREAD

**Issue by msantavy** [triceo/robozonky#53]
Vzhledem k tomu že Robozonky stejně čtou data ze Zotify, navrhuji, aby si data o Tržišti nejdřív načetly ze Zotify, a až pokud bude existovat nějaká relevantní půjčka daná strategií, přihlásily se na Api Zonky a po dalších kontrolách provedly investici.

Má to několik výhod:
 - Výrazné zmenšení zátěže serverů Zonky, tudíž menší potencionální problémy ze strany Zonky
 - Prakticky vyřešení dalších problémů Robozonky (servery zonky v Maintenanci, usínání, ...)
 - Zmenšení zátěže počítače, na kterém Robozonky běží

Nevýhoda:
 - Nevím, jak by se toto dalo aplikovat v případě Drools tabulek... Workaround by byl, že by jely postaru.

Předpokladem pro tyto výhody je, že jsou Robozonky převážně používány pro půjčky, které velmi rychle mizí. Pokud by někdo investoval do jakékoliv (tj. bez omezení např délky) A++, A* apod. byl by rozdíl nulový, takové půjčky jsou na tržišti stále. 

Nabízím v případě zájmu i implementaci této featury.

**Comment by triceo** [comment]
To je zajímavá myšlenka - přiznám se, že mne to nenapadlo. Zamyslel jsem se nad tím, a vidím tam dva obtížně překonatelné problémy:

- Součástí strategie jsou i parametry související s aktuálním zůstatkem. Ten je možné zjistit pouze po přihlášení.
- Do některých půjček, které jsou na tržišti, již není možné investovat, protože už jsme do nich investovali. Tuhle informaci také zjistíme pouze po přihlášení.

Obojí se samozřejmě dá "vyřešit" tak, že by si _RoboZonky_ pamatoval svůj stav mezi jednotlivými spuštěními. To je ale relativně nespolehlivé, např. zůstatek se mezitím mohl jednoduše změnit z mnoha důvodů. Nicméně mne zajímá, jak byste to řešil Vy.

Co se samotného přihlašování týká, nepovažuji to za nijak zásadní problém - díky podpoře pro OAuth můžete neustálé přihlašování z větší části obejít.

**Comment by msantavy** [comment]
> Součástí strategie jsou i parametry související s aktuálním zůstatkem. Ten je možné zjistit pouze po přihlášení.
Ano, myslel jsem to tak, že přes Zotify by se zjistilo, jestli vůbec je kam investovat a má smysl se přihlašovat. V mém případě to jsou max promile případů. Pokud se pak zjistí, že nejsou peníze, budiž. 

> Do některých půjček, které jsou na tržišti, již není možné investovat, protože už jsme do nich investovali. Tuhle informaci také zjistíme pouze po přihlášení.
Tady bych použil můj předpoklad, že robotem se investuje do půjček, které jsou rychle pryč. Tj. pokud i v tomto případě Zotify dovolí a proběhne login navíc, zjistí se, že už je zainvestováno a Robozonky skončí.

Možná jsem se špatně vyjádřil - nemyslel jsem Zotify jako jediný zdroj dat, ale jako primární, který když nenajde nic k investování, skončí, když najde, proběhne standardní proces, který také může skončit bez akce.

>  by si RoboZonky pamatoval svůj stav mezi jednotlivými spuštěními
Aha, takže TEN Robozonky... :). To se mi taky nelíbí, nedělal bych to. Ten samý problém ale máte i s případným usínáním. 

> přihlašování nepovažuji to za nijak zásadní problém
Asi ne, ale vyřeší se tím by design problém s chybami při údržbě Zonky webu (to asi v tu dobu ani půjčky nepřibývají), a nebudou roboti (aspoň Robozonky) trackovatelní ze strany Zonky. Netuším, kolik problému jim způsobuje spousty neustále připojujících se robotů, kolik vůbec různých robotů existuje. Ale robota jsem začal považovat za nutného poté, co když Zotify zjistil, že je nová zajímavá půjčka, jsem se asi minutu nebyl schopný sám přes web přihlásit, jak byl přetížený (což se tímto nevyřeší), nicméně to ukazuje na omezenost jejich vybavení.

**Comment by triceo** [comment]
Jsem trochu skeptický k tomu, co ze strategie ještě užitečného zbyde, pokud nemáme informace o portfoliu a zůstatku. Ale dobře, pojďme to zkusit - připravte ve volné chvíli pull request, který vloží takové chování sem, před login:
https://github.com/triceo/robozonky/blob/master/robozonky-app/src/main/java/com/github/triceo/robozonky/app/App.java#L78

Pár poznámek:

- Očekávám, že budou v novém řešení fungovat obě strategie. (Jak `simple`, tak `drools`.) Ve stávajícím API nevidím překážky, bude jen potřeba vhodně vyplnit `PortfolioOverview`.
- Jsem zvyklý udržovat poměrně vysokou kvalitu návrhu a kódu. Připravte se, prosím, na to, že nad Vaším pull requestem proběhne diskuse a rozhodně nebude zamergován automaticky. :-)
- Pokud byste musel při řešení problému dělat nějaká zásadní návrhová rozhodnutí, poraďte se předem. O to pak bude diskuse nad pull requestem jednodušší.
- Nedělejte jiné změny než ty, které jsou pro Vaše řešení naprosto nezbytné. Pokud chcete implementovat ještě něco dalšího, rád se s Vámi podívám na další pull request.

Hodně štěstí, těším se na výsledek!

**Comment by msantavy** [comment]
Zatím jsem se k tomu ještě nedostal. Myslíte tedy, že Robozonky se používá i na investování těch půjček, které nemizí rychle? Pak by to opravdu moc nepomohlo (mohly by se načítat data z *.invested souborů). 

Všiml jsem si ale jiného Pull requestu - na Push Bullets. Což zní opravdu zajímavě, a přebilo by to zřejmě tento můj nápad...

**Comment by triceo** [comment]
Osobně si myslím, že primární use case pro _RoboZonky_ je "nasadit na NAS v rohu ve sklepě, nechat pracovat, inkasovat úroky". Osobně ho používám právě tak - naprosto bez zásahu, kompletní kontrola nad portfoliem, nulová lidská interakce s webem Zonky. 

Je tady poměrně solidní argument, proč by to nemělo být jinak - v závislosti na tom, kolik máte rozinvestováno, se Váš strávený čas jednoduše nemusí vyplatit. Pokud v tom máte 10.000,- a tedy z toho za rok získáte 1.000,-  (buďme optimističtí), pak byste na Zonky musel strávit asi sekundu denně, aby vám ten "zisk" zaplatil vynaložený čas. 

Samozřejmě nevylučuji, že někoho baví se webem proklikávat, ale já to nejsem - a domnívám se, že ani drtivá většina ostatních uživatelů robota. Nicméně tohle už je čirá spekulace.

**Comment by triceo** [comment]
Teď, co jsem vyřešil #57, bude případná implementace téhle feature o dost jednodušší - Zotify API je dostupné mnohem dřív a zpracovává se s prodlevou, takže nějakou dodatečnou analýzu už bude relativně snadné dodělat.

**Comment by triceo** [comment]
A když už to bylo tak jednoduché, tak jsem to i udělal. :-)

**Comment by msantavy** [comment]
Zjišťujete, jestli od minula přibyla nějaká půjčka, pokud ne, k Zonky se vůbec nepřipojí. Ok, taky možnost. V mém případě bych se musel probírat rozhodovacíma tabulkama (které nepoužívám a neznám), takhle je to jednodušší. Díky za implementaci.
