### ISSUE TITLE
Zpracování textu příběhu

### ISSUE THREAD

**Issue by msantavy** [triceo/robozonky#54]
Robozonky by mohly ve strategii i brát v potaz text příběhu. Nechci totiž dávat peníze do půjček, u které se žadatel neobtěžoval zadat jakýkoliv text. Dává tak možná najevo, že to ani splatit nehodlá. A koneckonců, Zonky staví na příbězích.

Jedno řešení by bylo zadat podmínku jako regulární výraz (např .{100,}). Je to sice trochu overkill, ale zas se tím dají odfiltrovat např příběhy psané CAPS LOCKEM, nebo skutečně se řídit dle klíčových slov.

V případě zájmu nabízím i implementaci.

**Comment by triceo** [comment]
Tady jsem na pochybách. To, jestli je něco napsáno velkými písmeny, nebo jestli to má X znaků, to může a nemusí být pro investory validní kritérium. Ten algoritmus, který tohle kontroluje, by tedy musel být extrémně flexibilní, aby si mohl kdokoliv implementovat prakticky jakékoliv chování. A tady si vážně nejsem jist, jestli něco takového vůbec v robotu chceme.

Jak daleko jít? Regulární výraz mi přijde jako příliš hrubý nástroj. A zpracování přirozeného jazyka neumím. :-)

**Comment by msantavy** [comment]
Já samozřejmě nemám statistiku o tom, které půjčky mají v budoucnu problémy se splácením. Zpracovatelných informací o půjčce moc není, všechno je schované pod rozdělením do ratingu. Kdybych investoval sám, bez robota, tyhle věci bych zahrnul do rozhodnutí, jestli poslat peníze nebo ne. Půjček je dost, víc než se dá investovat, proto já bych tuto možnost ocenil. Tolik mé zdůvodnění, resp. doplnění.

Regulární výrazy jsou hrubá metoda, uznávám. Jsou různé teorie na sémantickou analýzu textu (LDA), zjišťování emocí apod. S tím ale nemám zkušenosti, a nevím, jestli relativně krátký text by na něco takového vůbec postačoval.
Implementaci LDA v Javě např v diplomce: https://dspace.vutbr.cz/xmlui/handle/11012/39994?show=full

**Comment by triceo** [comment]
Ve verzi 4 přibyde nová strategie, která bude umět příběhu částečně porozumět.
