### ISSUE TITLE
RESTEasy warning

### ISSUE THREAD

**Issue by AlmerCz** [triceo/robozonky#56]
Pri stusteni dostavam nasledujici warning:

17:58:18.624 WARN  RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider is already registered.  2nd registration is being ignored.

**Comment by triceo** [comment]
Já taky. :-) Ve volné chvíli se zkusím zamyslet, jak by se toho dalo zbavit - každopádně na funkci to nemá vliv.

Díky za nahlášení!

**Comment by AlmerCz** [comment]
Je mozne ze to je Java/Architecture dependent? Ja bezim na JDK 1.8.101 a mac os x (10.10)...
