### ISSUE TITLE
Zonky zavedlo CAPTCHA

### ISSUE THREAD

**Issue by kudykam** [triceo/robozonky#57]
Nově bude na serveru zonky umístěna captcha první 2 minuty po vložení půjčky.
Bude umět robozonky captchu obejít? 
Nevím jak to Lucka myslela tím blokováním robotů, doufám že mě nebloknou protože jej používám, ale jen myslela tu captchu. Možná by měla Lucie technické řešení přetížení Zonky nechat na odbornících a nevymýšlet kraviny které nic nevyřeší...

**Comment by triceo** [comment]
Ještě nevím, jestli bude možné captchu obejít. Budu muset prostudovat skutečnou implementaci, až se objeví.
Nicméně ještě během víkendu vydám novou verzi, která bude brát v potaz jen půjčky starší 2 minut - takže _RoboZonky_ bude dál fungovat.

**Comment by triceo** [comment]
Rozhodl jsem se, že CAPTCHA nebudu obcházet. (Více info k tomu v příspěvku ve skupině na Facebooku.) V rámci řešení tohoto problému během víkendu vydám verzi 1.5.0, která bude ignorovat půjčky mladší 2 minut.

**Comment by kudykam** [comment]
Bez obejití CAPTCHA myslím nemá smysl tento skript dál vyvíjet protože nic nezainvestuje.

**Comment by triceo** [comment]
@kudykam Zainvestuje toho podstatně méně, pravda. Nicméně ne každý jde výhradně po A/B/C/D do 36 měsíců. :-)
