### ISSUE TITLE
Logy do souboru nejsou kompletni

### ISSUE THREAD

**Issue by AlmerCz** [triceo/robozonky#61]
V nejakych pripadech se mi stava, ze logy zapisovane do souboru nejsou kompletni ... Resp. je tam jenom cast.

A je jedno, jaky lvl je nastaven (konkretne ja mam nastaveno logovani do dvou souboru zaroven - trace a info level.

14:52:50.446 [main] INFO  com.github.triceo.robozonky.app.App RoboZonky v1.4.2 loading.
14:52:57.772 [main] INFO  o.d.c.k.b.impl.KieRepositoryImpl KieModule was added: MemoryKieModule[releaseId=org.default:artifact:1.0.0-SNAPSHOT]
14:52:57.818 [main] INFO  com.github.triceo.robozonky.app.App ===== RoboZonky at your service! =====
14:52:58.452 [main] WARN  o.jboss.resteasy.resteasy_jaxrs.i18n RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider is already registered.  2nd registration is being ignored.
<<< EOF

**Comment by msantavy** [comment]
Není zbylá část v dalším log souboru? Pokud máte rozdělení log souborů po minutách, tento máte v xxxx1452.log, pokračování v xxxx1453.log.

**Comment by triceo** [comment]
Kromě toho, co říká @msantavy (a co je taky asi nejpravděpodobnější), se nabízí i možnost, že prostě RoboZonky spadnul někdy uprostřed běhu - musel by to ale být pád skutečně tvrdý, třeba zabití operačním systémem třeba z důvodu SEGFAULtu v Javě. To je ale velmi nepravděpodobné.

**Comment by triceo** [comment]
@AlmerCz, přetrvává problém?

**Comment by AlmerCz** [comment]
@triceo nakonec mel @msantavy pravdu:D sem se nekoukal nikdy do dalsiho logu:)

**Comment by triceo** [comment]
@AlmerCz I tak díky za nahlášení!
