### ISSUE TITLE
Not investing - Amount to invest is more than balance

### ISSUE THREAD

**Issue by jirrick** [triceo/robozonky#62]
Ahoj, kdyz jsem chtel vyzkoset jak funguje to dvouminutove cekani ve verzi 1.5.0, tak jsem narazil na pomerne neocekavane chovani modulu investor. V penezence jsem mel 260Kc, objevila se pujcka, ktera zapadala do porfolia, ale robozonky nezainvestovalo, protoze jsem mel mene penez nez maximalni mozna investice (600Kc podle strategie). Cekal bych, ze se misto chybove hlasky pouzije nejvetsi mozna dostupna castka (200Kc). Nebo mam neco spatne v konfiguraci? 

`Investor - Current share of unpaid loans with a given rating is: {AAAA=0.0339, A=0.1877, B=0.2312, AAA=0.1054, D=0.2002, AA=0.0992, C=0.1423, AAAAA=0.0000}.`
`SimpleInvestmentStrategy - According to the investment strategy, the portfolio is low on following ratings: [C, AA, A].`
`Investor - Strategy recommends the following unseen loans: [Loan{id=46007, termInMonths=42, userId=60814, amount=250000.0, rating=AA}].`
`SimpleInvestmentStrategy - Recommended investment range of <200; 600> CZK.`
`Investor - Not investing into loan 'Loan{id=46007, termInMonths=42, userId=60814, amount=250000.0, rating=AA}', 600 CZK to invest is more than 260 CZK balance.`

**Comment by triceo** [comment]
Hmm, to bude skutečně chyba. Vyřeším dnes nebo zítra.

**Comment by triceo** [comment]
Problém vyřešen nově vydanou verzí 1.5.1. Přidal jsem i test, takže už by se to nemělo opakovat.
Díky za nahlášení!
