### ISSUE TITLE
Verze robozonky ve wiki

### ISSUE THREAD

**Issue by linuzh** [triceo/robozonky#63]
https://github.com/triceo/robozonky/wiki/Selektivn%C3%AD-pasivita-alias-%22hibernace%22
Píšete, že ve verzi 1.6.0 je hibernace, nemá být 1.5.0? Nikde verzi 1.6.0 nevidím

**Comment by triceo** [comment]
To je v pořádku, protože verze 1.6.0 ještě nějakou dobu nebude. :-) Napsal jsem ten článek trochu dopředu, ale ta vlastnost už je na Githubu implementovaná.
