### ISSUE TITLE
Spani na mene nez 120 seconds

### ISSUE THREAD

**Issue by AlmerCz** [triceo/robozonky#66]
Ahoj,
mam navrh na zlepseni - jelikoz zotify ma plus minus cas, ve kterem se nektera pujcka zverejnila, pak robozonky nemusi spat 120 sec ale t=120-now od zverejneni pujcky (tj. pouze rozdil).

**Comment by triceo** [comment]
@AlmerCz, možná jsem to někde špatně vysvětlil. 

_RoboZonky_ usne (= přestane se připojovat na Zonky) jen tehdy, pokud vyhodnotí, že na Zotify není nic nového a že se během příštích 2 minut nic nového nestane. (Tj. nečeká žádná půjčka, která by byla chráněná CAPTCHou.) Nicméně i během "spánku" neustále kontroluje Zotify. Pokud se na Zotify stane něco zajímavého, jako třeba že se objeví nová CAPTCHou chráněná půjčka, tak spát nebude a bude se normálně připojovat na Zonky. A to až do doby, než ta půjčka zase zmizí, kdy usne.

Myslím tedy, pokud jsem původní komentář pochopil dobře, že chování je správné a není co řešit. Pro jistotu se podívám, jak jsem to popsal na Wiki, a případně to upravím. Díky za nahlášení!
