### ISSUE TITLE
Lepší zpracování captcha problému bez obcházení

### ISSUE THREAD

**Issue by kudykam** [triceo/robozonky#67]
Ahoj,
Vzhledem k  tomu že od spuštění captcha se mi podařilo odchytit asi jen dva obchody s délkou do 36 měsíců (a to sedím u pc skoro nonstop a mám aktivní upozornění i pusbullet) považuji tento problém za závažný. Současný stav čekání 2 minut je o ničem.
Navrhuji aby robot fungoval tak jako doposud a pokud objeví nový obchod dle pravidel tak automaticky otevře prohlížeč se stránkou a již zadanými přihlašovacími údaji tak aby stačilo jen zadat částku a odkliknout captchu.
Je to možné?

**Comment by triceo** [comment]
Zdravím,

pro tenhle případ doporučuji použít [Zonkoid](https://play.google.com/store/apps/details?id=eu.urbancoders.zonkysniper&hl=en). Upozorňuje a umožňuje přihlášeným opsat CAPTCHA a přihlásit se. 

_RoboZonky_ nikdy žádnou přímou interakci s lidmi mít nebude. Je to robot, serverová aplikace.

**Comment by kudykam** [comment]
zonkoid taky není ideální, upozornil mě na novou investici asi 15 minut poté co byla vydána.. Já vím že robot je jen skript, ale i ten dokáže otevřít prohlížeč se zadanou emailovou adresou ne? žádná interakace s uživatelem u toho není nutná.
