### ISSUE TITLE
Dosud nezainvesovaný rating

### ISSUE THREAD

**Issue by PerDeDor** [triceo/robozonky#8]
Pokud zatím nemám například u ratingu AA žádnou investici, tak RoboZonky nepozná, že u toho ratingu mám zatím 0% a neoznačí tento rating jako low on portfolio, tudíž ani nehledá v tržišti, ačkoliv by měl podle strategie.

**Comment by triceo** [comment]
Díky za nahlášení!

V testech se mi bohužel nic takového neobjevilo - můžete poslat nastavení svojí strategie? Trochu mi to pomůže ten problém najít.

**Comment by PerDeDor** [comment]
Moje strategie je nasledovna:

targetShare.AAAAA            = 0.2
targetShare.AAAA              = 0.2
targetShare.AAA                = 0.2
targetShare.AA                  = 0.15
targetShare.A                     = 0.1
targetShare.B                     = 0.05
targetShare.C                    = 0.05
targetShare.D                    = 0.05

Pricemz mi ukazuje low on portfolio pouze AAAA, kde mam 17%. Ale u AAAAA nebo A nemam zadnou investici, tedy 0%,  ale RoboZonky je nehleda.

**Comment by triceo** [comment]
Díky, našel jsem to a opravu vydám někdy zítra.

**Comment by triceo** [comment]
Až se to dostane na mirror, bude to k dispozici tady:
http://search.maven.org/remotecontent?filepath=com%2Fgithub%2Ftriceo%2Frobozonky%2Frobozonky-app%2F1.0.3.Final%2Frobozonky-app-1.0.3.Final-dist.zip
