### ISSUE TITLE
Rozšíření informací o půjčce v e-mailu

### ISSUE THREAD

**Issue by AscifiA** [triceo/robozonky#85]
Příjemný den, Lukáši.
emaily nyní procházejí perfektně, po přidání From do konfiguračního souboru, je vše OK, Děkuji.

Měl bych však jeden návrh k e-mailu:
Když mám propojení se Zonkoidem a Robozonky deleguje půjčku, pak info v emailu je pouze toto (Viz níže). Informace o půjčce jsou jen navržená částka a číslo půjčky (a link na ni).

Navrhuji přidat ještě Rating a měsíce - půjčky (do obsahu e-mailu), protože pokud zrovna nejsem na zonkoidu, nebo je zonkoid neaktivní v mobilu, musí se na základě e-mailu hledat detail půjčky na internetu, čímž se ztrácí čas.
Pokud by v mailu bylo vidět přímo i Rating a Délka splácení, bylo by rovnou jasné, zda vůbec chci jít na internet a investovat, či zda si toho nemusím všímat...

Přičemž Robozonky tyto informace ve chvíli odeslání e-mailu zná, viz:
07:43:06.097 [main@6492@mskwin01] DEBUG c.github.triceo.robozonky.ZonkyProxy Asking to confirm investment: Recommendation{loanDescriptor=LoanDescriptorImpl{loan=Loan{id=67301, termInMonths=60, userId=87425, amount=290000.0, rating=AAA}, captchaExpirationDateTime=2017-01-13T14:40:07.565+01:00}, recommendedInvestmentAmount=200, confirmationRequired=true}.

Info z e-mailu:
RoboZonky Vás tímto informuje o následujícím:

Půjčka s následujícími parametry byla předána k investování jiným nástrojem:

- Číslo půjčky:                67301
- Navržená výše investice:     200,- Kč
- Cílový nástroj:              Zonkoid / Zonkios

Informace o této půjčce jsou dostupné na následující adrese:
https://app.zonky.cz/#/marketplace/detail/67301/

Zůstatek na Zonky účtu je 465,- Kč.

**Comment by triceo** [comment]
Zdravím, to rozhodně není problém. Uvidím, jestli se ve 2.0.3 objeví nějaká chyba, že bych to spláchnul s ní. Jinak bych to přidal do 3.0.0, až se mi podaří dodělat démona.

**Comment by AscifiA** [comment]
OK, rozumím, díky :-)
