### ISSUE TITLE
Nechodí notifikace na Zonkoid

### ISSUE THREAD

**Issue by pastelka** [triceo/robozonky#87]
Dobrý den,

přidal jsem parametr -x zonkoid:XXXXXX, ale žádná notifikace nedorazila, přestože aplikace do logu zapíše:

robozonky.20170125231749375.delegated

Kde může být problém? Lze notifikace nějak otestovat?

děkuji

Pastelka

**Comment by triceo** [comment]
Dobrý den,

otestovat to nejde, ale udělal jsem si na to issue #88 a v budoucnosti to tam dodělám.

Pokud pošlete log, podívám se, jestli z něj něco podivného nekouká - ale pokud byla investice správně delegována, tak se taky klidně mohlo stát, že zrovna nefungoval Zonkoid.

**Comment by pastelka** [comment]
Dobrý den,

 

Logy mám nastaveny pouze na INFO. Má smysl vám je posílat? Nebo mám nastavit vyšší logování a počkat na další problém.

 

Děkuji

**Comment by triceo** [comment]
Z INFO nejspíš nic nezjistím, podrobnější log bude zapotřebí. Nicméně vzhledem k tomu delegování asi ani podrobný log nepomůže, protože to vypadá, že ta operace proběhla úspěšně.

**Comment by triceo** [comment]
Zavírám s tím, že do RoboZonky 3.0.0 dodělám možnost testování funkčnosti notifikací.
