### ISSUE TITLE
robozonky SYNOLOGY

### ISSUE THREAD

**Issue by Jannicek** [triceo/robozonky#89]
Ahoj, můžete mi prosím poradit, jak na SYNOLOGY NAS nastavit?
Nastavil jsem jako úlohu v Plánovači úloh. /volume1/robozonky/robozonky.sh
Ale vrací se mi:
Úloha: RoboZonky
Počáteční čas: Fri, 27 Jan 2017 22:42:02 GMT Koncový čas: Fri, 27 Jan 2017 22:42:02 GMT Aktuální stav: 127 Standardní výstup/chyba:
/volume1/robozonky/robozonky.sh: line 4: /bin/java: No such file or directory

**Comment by triceo** [comment]
Musíte si v Synology package centru nainstalovat Java 8. Pak by měl tenhle problém zmizet.

**Comment by Jannicek** [comment]
Díky za reakci. Mám nainstalováno Java 8. Ale i tak nic neproběhne. Do linuxu moc nevidím, takže omluvte prosím pokud bych psal nějaké kraviny. Java 8 je v var/packages/Java8/target/j2sdk-image/jre.
Ale chyba odkazuje na  line 4: /bin/java: No such file or directory. Ale fakt nevím jestli to nejsou informace úplně mimo. Děkuji za pomoc.

**Comment by triceo** [comment]
Potřebujete správně nastavit cestu k instalaci Javy. Jestli máte Javu ve `/var/packages/Java8/target/j2sdk-image/jre`, zkuste spouštět RoboZonky takhle:
`JAVA_HOME=/var/packages/Java8/target/j2sdk-image/jre robozonky.sh`.

Alternativně by mohlo někde v Synology jít nastavit JAVA_HOME jako proměnná prostředí, abyste jí nemusel pokaždé uvádět.

**Comment by Jannicek** [comment]
Díky jsme o kus dál. Myslím, že už poslední triviální dotaz. "robozonky.sh: command not found". Předpokládám, že musím někde definovat link aby bylo možné "robozonky.sh" spustit odkudkoli pouze příkazem robozonky.sh. Nebo jsem úplně mimo? Díky za trpělivost a pomoc.

**Comment by triceo** [comment]
To do značné míry závisí na Vás. Z výše uvedeného usuzuji, že máte RoboZonky v adresáři `/volume1/robozonky` - v takovém případě můžete RoboZonky spustit buď prakticky odkudkoliv zadáním celé cesty k souboru, tj. `/volume1/robozonky/robozonky.sh/`, nebo pouze `robozonky.sh`, pokud jste se předtím přepnul do adresáře `/volume1/robozonky/`. Tohle už nemá s robotem nic společného, tohle jsou základy použití operačního systému.

**Comment by khostri** [comment]
Na Synology mi cesta k javě také nefunguje. Respektive ve vašem případě nefunguje cesta k bash.
Jedná se skutečně spíše o schopnost používání OS. Pro zjednodušení - předpokládám, že chcete používat aktuální alfa verzi robozonky, že jí chcete mít puštěnou na synology jako démona, že chcete použít zabezpečené úložiště přihlašovacích údajů. A máte k dispozici cfg soubor strategie, kterou zamýšlíte využít:
1) v terminálu musíte nejprve pustit Zonky ručně. Jelikož evidentně nemáte bash v cestě nebo ho to nenajde, pustíte to tak, že před robozonky.sh přidáte sh. A Javu také nemáte v cestě, jak jsem pochopil, proto bych ve vašem případě nejprve navrhoval změnit textovým editorem robozonky.sh takto:
`#!/bin/bash
BASEDIR=/volume1/robozonky      respektive adresář, kde máte robozonky
JAVA_HOME="/volume1/@appstore/Java8/j2sdk-image"  adresář, kde máte instalovánu javu
JAVA_OPTS="$JAVA_OPTS -Dlogback.configurationFile=logback.xml -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true"
cd $BASEDIR
$JAVA_HOME/bin/java $JAVA_OPTS -jar $BASEDIR/robozonky-app-3.0.0-alpha-1.jar "$@"`

nyní v terminálu spusťte robozonky takto:
`sh robozonky.sh -u loginame@domain.com -p heslo -r single -s strategie.cfg`
2) dále si zabezpečíte úložiště podle návodu na wiki:
`$JAVA_HOME/bin/keytool -storepasswd -keystore robozonky.keystore -storetype jceks`
zde změníte heslo úložiště na nějaké jiné, než máte na zonky 
3) dále nastavíte spouštění démona tak, aby se spustil po restartu:
V Ovládacích panelech na Synology spusťe Task scheduler. Zvolte Create - triggered task.
zadáte jméno úlohy dle uvážení, vás jako uživatele, event nastavíte boot-up
V task settings do pole User defined script dáte toto:
`/volume1/robozonky/robozonky.sh -g robozonky.keystore -p nove_heslo_uloziste -r daemon -s strategie.cfg`

samozřejmě cesta bude odpovídat vašemu adresáři.

Teď už by se vám měl postupně zvětšovat log v adresáři robozonky a vše by mělo běžet. Zatím uživatelský démona neukončíte, respektive musel byste jej killnout (killall robozonky.sh v terminálu). Po restartu se démon znovu nastartuje.

**Comment by triceo** [comment]
@khostri Wow! Nechcete to upravit do podoby článku ve Wiki? Myslím, že by takový pěkný popis pomohl mnohem více lidem.

**Comment by triceo** [comment]
Zavírám, neboť se nejedná o problém v robotu, který by se dal jakkoliv opravit.
