### ISSUE TITLE
Robozonky 2.0.4 - Synology

### ISSUE THREAD

**Issue by khostri** [triceo/robozonky#90]
Ahoj
Robozonky ve stávající stable verzi mi funguje v pohodě, byť na Synology jsem musel v bash scriptu přepsat proměnné PATH na konkrétní cestu.
Co mi ale nefunguje ani z terminálu je zabezpečené úložiště. Při použití Keystore to pořád hlásí, že je špatné heslo, nebo že někdo s úložištěm manipuloval:

> keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect

Stejná situace je když jsem chtěl keystore naimportovat a vyexportovat jinam. Můžete mi prosím poradit, zda náhodou robozonky pro keystore nevytvoří jiné heslo, než je heslo k účtu?

**Comment by triceo** [comment]
Podívám se na to koncem týdne a pokusím se zjistit, kde je chyba. Díky za report!

**Comment by triceo** [comment]
@khostri zkusil jsem to rychle u sebe na laptopu a všechno funguje, jak má. _RoboZonky_ vytvoří nový keystore, a použije pro něj stejné heslo, jako je přihlašovací heslo do Zonky. To pak úspěšně změním přesně podle návodu na wiki.

Na heslo se samozřejmě ptát nebudu, ale možná bych jen doporučil překontrolovat, že neobsahuje nějaké znaky, které by v terminálu bylo potřeba escapovat. Tahle chybová hláška se vypisuje skutečně většinou v případech, kdy je špatně zadané heslo.

**Comment by khostri** [comment]
Viz issue s verzí Alpha - v heslu nesmí být $, pak to funguje
