### ISSUE TITLE
Dalsi filtry - castecne porozumeni pribehu

### ISSUE THREAD

**Issue by AlmerCz** [triceo/robozonky#93]
Myslim, ze by bylo fajn, kdyby robozonky umelo rozlisovat:
- zdroj prijmu (zamestanec, duchodce, osvc,...)
- lokalitu pujcky (kraj)
- ucel pujcky (refinance, auto-moto, elektronika, ...)
- dalsi tagy - overeny v registrech / overeny prijem / ... (ne dalsi Karel:D)

Castecne by to suplovalo parsovani pribehu.

**Comment by triceo** [comment]
@AlmerCz Zajímavé. Jak byste si představoval, že by to vypadalo?

Myslím si, že kdyby to mělo být v souboru se strategií, že už by to potom bylo moc složité. Jak třeba ignorovat "všechna A++ do 60 měsíců, kde žadatel je z Ústí nebo z Varů, ale není to podnikatel?" :-)

**Comment by AlmerCz** [comment]
@triceo Nejak takto:)

Vazne - napr. ja dost filtruju a nektere proflakle lokace nepujcuju (ustecky a moravskoslezky kraj), taky rizikovym skupinam (duchodci, materska).

Jelikoz vsechny skupiny v .cfg jsou rekneme ve vztahu AND , tak by zalezelo jenom na zapise. Dovedu si predstavit jako negativni, tak pozitivni formu - napr. allowedLocations = {Praha, Jihomoravsky, Moravskoslezsky}.

**Comment by triceo** [comment]
Hmm. Zamyslím se nad tím potom, co dodělám robota. Díky za nápad!

**Comment by AlmerCz** [comment]
Jinak pokud se bavime o tech problemech vyse: 
- da se refaktorovat ten konfigurak. Napr. tak, ze nektere min, max hodnoty se daji udelat jako {min,max}, kde -1 je no limit
- ty komplikovanejsi a narocnejsi rozhodovaci pravidla (napr. pro duchodce max 50tis v ratingu AAAAA-AAA, 10tis. v ostatnich) se muzou udelat i pres Drools, ale chtelo by to vedet, jake vsechny hodnoty se parsujou a daji se pouzit pri sestavovani pravidel
-  samozrejme by to chtelo rozsirit o ty dalsi atributy - region, mainIncomeType, purpose (ty jsou v JSON) a pak overeny prijem a overeny v registrech (nenasel jsem ale v JSONu, verification v html)

**Comment by triceo** [comment]
@AlmerCz Všechny tyhle atributy už máme implementované v doménovém modelu, takže zpřístupnit je do strategie nebude problém. Otázka pořád zůstává, jak.

Na současné "simple" strategii mám rád přesně to "simple" - je to tak jednoduchý, že to pochopí i uživatel počítačů neznalý, kterému není jednoduché vysvětlovat AND, OR, uzávorkování. Druhak bych nerad rozbil lidem strategie, co jim doteď fungovaly. Nicméně souhlasím, že by bylo dobré nějakou sofistikovanější strategii mít.

Takže vidím dvě možnosti:

- Nová implementace strategie, která by umožnila nějaké lidsky příjemné nastavení, třeba prostřednictvím DSL. ("Pokud je rating A a žadatel je OSVČ s ověřeným příjmem z Ústeckého kraje, pak investovat X Kč.")
- Nechat "simple" strategii tak, jak je, a implementovat "před-filtr". V podstatě podobně, jako v simple strategii, by se řeklo, že pro rating X zakazujeme půjčky takové a takové.

První možnost je opravdu hodně práce, ale Drools v tom pomůžou. Druhá možnost se mi ale líbí daleko víc - nechává strategii starost o peníze, a i přesto umožňuje lidem některé konkrétní lidské situace ignorovat.

Co myslíte, @AlmerCz ?

**Comment by AlmerCz** [comment]
@triceo chapu umysl - ale teoreticky jdou implementovat obe moznosti.

Pridanim "pred-filtru" by se daly teoreticky odstranit nektere moznosti globalne. Napr. rekneme ze "OSVC" bych nikdy nebral (aniz bych znal rating). Lidi by tam mohli mit "simple", opravdu simple.

Na druhe strane, pokud se vytahnout dane "indikatory" do Drools, tak se implementovat i sofistikovanejsi strategie - napr. je-li OSVC, tak brat pouze Praha+Stredocesky, nebo u Duchodce brat pouze pujcku do 24 mesicu a ratingu AAAA+.

Nebo je to nesmysl?

**Comment by triceo** [comment]
@AlmerCz Nesmysl to rozhodně není! Myslím, že by bylo super tam takovouhle pokročilou strategii mít. 

Jen si budu ještě chvíli lámat hlavu s tím, které z těchhle vlastností se snažit nějak zpřístupnit i v simple, a které už prostě odkázat na složitou strategii, třeba v Drools.

**Comment by AlmerCz** [comment]
@triceo davalo by mi to smysl tak, ze a) prida se druhy soubor, ktery bude jako predfilter (a je jedno, zda bude mit negativni filter - tj. tyto nepoustej nebo pozitivni filter - tj. pouze tyto poustej b) zakomponovat to do std. cfg filu. Tam by asi davalo mit negativni filter, kdy nezvoleni je defacto propusteni vsech.

**Comment by triceo** [comment]
Ve verzi 4 přibyde nová strategie, která velkou část tady diskutovaných věcí bude umět.
