### ISSUE TITLE
Nenačte parametry robozonky.cli

### ISSUE THREAD

**Issue by linuzh** [triceo/robozonky#97]
Ahoj,
verze 3.0.0 běží ok a při přechodu na verzi 3.0.1 píše problém "The following option is required: -p, --password"

Výpis z logu:
08:30:54.020 [main@24427@NAS] DEBUG c.g.triceo.robozonky.app.Exclusivity Acquiring file lock: /tmp/robozonky.lock.
08:30:54.034 [main@24427@NAS] DEBUG c.g.triceo.robozonky.app.Exclusivity File lock acquired.
08:30:54.290 [main@24427@NAS] DEBUG com.github.triceo.robozonky.app.App Current working directory is '/share/CACHEDEV1_DATA/homes/zdenek/robozonky'.
08:30:54.395 [main@24427@NAS] DEBUG c.g.t.r.app.notifications.Events Firing class com.github.triceo.robozonky.api.notifications.RoboZonkyStartingEvent.
08:30:54.395 [main@24427@NAS] TRACE c.g.t.r.app.notifications.Events Registering event listeners for class com.github.triceo.robozonky.api.notifications.RoboZonkyStartingEvent.
08:30:54.412 [main@24427@NAS] DEBUG c.g.t.r.app.util.ExtensionsManager Retrieving service loader for 'interface com.github.triceo.robozonky.api.notifications.ListenerService'.
08:30:54.417 [main@24427@NAS] DEBUG c.g.t.r.app.util.ExtensionsManager Using extensions folder: '/share/CACHEDEV1_DATA/homes/zdenek/robozonky/extensions'.
08:30:54.510 [ForkJoinPool.commonPool-worker-1@] DEBUG c.g.t.r.a.n.ListenerServiceLoader Processing 'class com.github.triceo.robozonky.app.management.JmxListenerService'.
08:30:54.528 [ForkJoinPool.commonPool-worker-1@] DEBUG c.g.t.robozonky.app.util.Scheduler Scheduling com.github.triceo.robozonky.api.Refreshable$1@1d3fd28 every 300 seconds.
08:30:54.534 [ForkJoinPool.commonPool-worker-1@] DEBUG c.g.t.r.a.n.ListenerServiceLoader Processing 'class com.github.triceo.robozonky.notifications.files.FileStoringListenerService'.
08:30:54.536 [ForkJoinPool.commonPool-worker-1@] DEBUG c.g.t.robozonky.app.util.Scheduler Scheduling com.github.triceo.robozonky.api.Refreshable$1@1f02b49 every 300 seconds.
08:30:54.537 [ForkJoinPool.commonPool-worker-1@] DEBUG c.g.t.r.a.n.ListenerServiceLoader Processing 'class com.github.triceo.robozonky.notifications.email.EmailListenerService'.
08:30:54.539 [ForkJoinPool.commonPool-worker-1@] DEBUG c.g.t.robozonky.app.util.Scheduler Scheduling com.github.triceo.robozonky.notifications.email.RefreshableNotificationProperties@1ecb022 every 300 seconds.
08:30:54.540 [ForkJoinPool.commonPool-worker-1@] DEBUG c.g.t.robozonky.app.util.Scheduler Scheduling com.github.triceo.robozonky.notifications.email.RefreshableEventListener@11d8fee every 300 seconds.
08:30:54.540 [pool-1-thread-1@] TRACE c.g.t.robozonky.api.Refreshable$1 New source found.
08:30:54.541 [pool-1-thread-1@] TRACE c.g.t.robozonky.api.Refreshable$1 New source found.
08:30:54.552 [pool-1-thread-1@] DEBUG c.g.t.r.n.e.NotificationProperties Read config file /share/CACHEDEV1_DATA/homes/zdenek/robozonky/robozonky-notifications.cfg.
08:30:54.566 [pool-1-thread-1@] TRACE c.g.t.r.n.e.RefreshableNotificationProperties New source found.
08:30:54.573 [pool-1-thread-1@] DEBUG c.g.t.robozonky.internal.api.State Reading state: /share/CACHEDEV1_DATA/homes/zdenek/robozonky/robozonky.state.
08:30:54.648 [pool-1-thread-1@] DEBUG c.g.t.r.n.e.RefreshableNotificationProperties Source successfully transformed to class com.github.triceo.robozonky.notifications.email.NotificationProperties.
08:30:54.648 [pool-1-thread-1@] DEBUG c.g.t.r.n.e.RefreshableNotificationProperties New value.
08:30:54.655 [pool-1-thread-1@] TRACE c.g.t.r.n.e.RefreshableEventListener New source found.
08:30:54.707 [main@24427@NAS] DEBUG com.github.triceo.robozonky.app.App Running Oracle Corporation Java v1.8.0_65 on Linux v3.4.6 (i386, 4 CPUs, en_US, UTF-8).
08:30:54.945 [main@24427@NAS] DEBUG c.g.t.r.a.c.CommandLineInterface Command line parsing ended with parameter exception.
com.beust.jcommander.ParameterException: The following option is required: -p, --password 
	at com.beust.jcommander.JCommander.validateOptions(JCommander.java:344)
	at com.beust.jcommander.JCommander.parse(JCommander.java:305)
	at com.beust.jcommander.JCommander.parse(JCommander.java:287)
	at com.github.triceo.robozonky.app.configuration.CommandLineInterface.parse(CommandLineInterface.java:72)
	at com.github.triceo.robozonky.app.App.execute(App.java:87)
	at com.github.triceo.robozonky.app.App.main(App.java:122)
08:30:54.976 [main@24427@NAS] TRACE com.github.triceo.robozonky.app.App Exit requested with return code ERROR_WRONG_PARAMETERS.
08:30:54.976 [main@24427@NAS] DEBUG c.g.t.robozonky.app.ShutdownHook RoboZonky terminating with 'ERROR_WRONG_PARAMETERS' return code.
08:30:54.977 [main@24427@NAS] DEBUG c.g.t.robozonky.app.util.Scheduler Shutting down.
08:30:54.979 [main@24427@NAS] DEBUG c.g.triceo.robozonky.app.Exclusivity File lock released.
08:30:54.979 [main@24427@NAS] TRACE c.g.triceo.robozonky.app.Exclusivity Lock file deleted successfully: true.

Všiml jsem si, že je asi chyba popisu v README, robozonky-daemon.cli se má přepsat na robozonky.sh a má být asi na robozonky.cli

**Comment by triceo** [comment]
To byla chyba ve 3.0.0 - omylem jsem vynucoval, že všichni musí používat `robozonky.cli` soubor. To jsem nikdy nechtěl, tak jsem to ve 3.0.1 "opravil."

Ve 3.0.1 je správný způsob spouštění `robozonky.sh @robozonky.cli`, čímž se soubor `robozonky.cli` načte.

**Comment by triceo** [comment]
(Alternativně samozřejmě `robozonky.sh -u ... -p ...`, zkrátka parametry obyčejně na příkazovou řádku.)

**Comment by linuzh** [comment]
Super, už to běží. Asi to na wiki není uvedeno.
Děkuji

**Comment by triceo** [comment]
`robozonky.cli` asi na Wiki ani uvádět nebudu. Někdy v budoucnu se to může hodit pro #96, ale zatím je to v podstatě k ničemu. Každopádně díky, že jste se ozval!
